[package]
name = "my-strategy"
version = "1.0.0"
edition = "2018"

[lib]
name = "my_strategy"
edition = "2018"

[dependencies]
log = "0.4.6"
env_logger = "0.6.0"
serde = "1"
serde_json = "1"
serde_derive = "1"
criterion = "0.2.5"
optimize = "0.1.0"
ndarray = "0.11.2"

[features]
enable_stats = []
enable_log = []
enable_render = []
enable_verbose_log = []
use_test_strategy = []

[profile.release]
debug = true

[[bench]]
name = "simulator"
harness = false

[[bench]]
name = "arena"
harness = false
